#!/bin/bash
# ============================================================
#  SOC Agent — Ubuntu / Linux Installer (Protected Install)
#  Must be run as root:  sudo bash install_agent.sh <MANAGER_IP> <AGENT_NUM> <MACHINE_NAME>
#  Example:              sudo bash install_agent.sh 192.168.1.100 5 lab-machine-5
#
#  Installs to: /opt/soc-agent/  (root:root, chmod 700 — users get Permission denied)
# ============================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SERVICE_NAME="soc-agent"
INSTALL_DIR="/opt/soc-agent"
REPO_URL="https://github.com/msuryawanshi05/soc-agent-deploy.git"

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$(id -u)" != "0" ]; then
    echo -e "${RED}ERROR: Must run as root. Use: sudo bash $0 $*${NC}"
    exit 1
fi

# ── Argument check ────────────────────────────────────────────────────────────
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "Usage: sudo bash $0 <MANAGER_IP> <AGENT_NUMBER> <MACHINE_NAME>"
    echo "Example: sudo bash $0 192.168.1.100 5 lab-machine-5"
    exit 1
fi

MANAGER_IP=$1
AGENT_NUM=$2
MACHINE_NAME=$3
AGENT_ID="agent-$(printf '%03d' $AGENT_NUM)"

echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  SOC Agent Installer (Ubuntu — Protected)${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${YELLOW}Manager IP :${NC} $MANAGER_IP"
echo -e "${YELLOW}Agent ID   :${NC} $AGENT_ID"
echo -e "${YELLOW}Hostname   :${NC} $MACHINE_NAME"
echo -e "${YELLOW}Install dir:${NC} $INSTALL_DIR"

# ── Step 1: Auto-detect Python ────────────────────────────────────────────────
echo -e "\n${GREEN}[1/7] Detecting Python...${NC}"
PYTHON=$(which python3 2>/dev/null || which python 2>/dev/null || true)
if [ -z "$PYTHON" ]; then
    echo -e "${RED}ERROR: Python 3 not found. Run: sudo apt install python3 python3-pip${NC}"
    exit 1
fi
echo -e "      Found: $PYTHON ($($PYTHON --version 2>&1))"

# ── Step 2: Check / install Git ──────────────────────────────────────────────
echo -e "${GREEN}[2/7] Checking Git...${NC}"
if ! command -v git &>/dev/null; then
    echo -e "      Git not found — installing..."
    apt-get install -y git -q
fi
GIT=$(which git)
echo -e "      Git: $GIT ($(git --version))"

# ── Step 3: Clone / update install directory ──────────────────────────────────
echo -e "${GREEN}[3/7] Setting up install directory ($INSTALL_DIR)...${NC}"
if [ -d "$INSTALL_DIR/.git" ]; then
    # Already cloned — pull latest
    git -C "$INSTALL_DIR" fetch origin --quiet
    git -C "$INSTALL_DIR" reset --hard origin/main --quiet
    echo -e "      Repository updated."
else
    rm -rf "$INSTALL_DIR"
    git clone "$REPO_URL" "$INSTALL_DIR" --quiet
    echo -e "      Repository cloned."
fi

# ── Step 4: Write .env ───────────────────────────────────────────────────────
echo -e "${GREEN}[4/7] Writing .env configuration...${NC}"
cat > "$INSTALL_DIR/.env" << EOF
# Auto-generated by install_agent.sh for $MACHINE_NAME
MANAGER_HOST=$MANAGER_IP
MANAGER_PORT=9000
AGENT_ID=$AGENT_ID
AGENT_HOSTNAME=$MACHINE_NAME
AGENT_SEND_INTERVAL=1
MONITOR_BROWSER_HISTORY=true
MONITOR_ACTIVE_WINDOW=true
MONITOR_USB_DEVICES=true
MONITOR_SHELL_COMMANDS=true
MONITOR_PROCESSES=true
EOF
echo -e "      .env written."

# ── Step 5: Install pip deps + compile .py → .pyc ────────────────────────────
echo -e "${GREEN}[5/7] Installing dependencies and compiling to .pyc...${NC}"
$PYTHON -m pip install -r "$INSTALL_DIR/requirements.txt" --quiet
$PYTHON -m compileall "$INSTALL_DIR" -q
echo -e "      Dependencies installed and .pyc compiled."

# ── Step 6: Lock down permissions ─────────────────────────────────────────────
echo -e "${GREEN}[6/7] Applying access restrictions...${NC}"
chown -R root:root "$INSTALL_DIR"
chmod -R 700 "$INSTALL_DIR"
echo -e "      Owner: root:root | Permissions: 700 (users get Permission denied)"

# ── Step 7: Register systemd service ──────────────────────────────────────────
echo -e "${GREEN}[7/7] Registering systemd service '$SERVICE_NAME'...${NC}"

systemctl stop    $SERVICE_NAME 2>/dev/null || true
systemctl disable $SERVICE_NAME 2>/dev/null || true

AGENT_SCRIPT="$INSTALL_DIR/agent/agent.py"
ENV_FILE="$INSTALL_DIR/.env"

cat > /etc/systemd/system/${SERVICE_NAME}.service << EOF
[Unit]
Description=SOC Platform Monitoring Agent
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$PYTHON $AGENT_SCRIPT
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable  $SERVICE_NAME
systemctl restart $SERVICE_NAME

# ── Verify ────────────────────────────────────────────────────────────────────
echo -e "${GREEN}[Verify] Checking service status...${NC}"
sleep 2
systemctl status $SERVICE_NAME --no-pager || true

echo ""
echo -e "${GREEN}✅ SOC Agent installed.${NC}"
echo -e "   Path     : $INSTALL_DIR (chmod 700 root:root)"
echo -e "   Service  : systemd $SERVICE_NAME — auto-start + auto-restart"
echo -e "   Updates  : agent pulls from GitHub on every boot"
echo ""
echo -e "${YELLOW}Commands:${NC}"
echo "  sudo systemctl status  $SERVICE_NAME"
echo "  sudo systemctl stop    $SERVICE_NAME   ← root only"
echo "  sudo journalctl -u     $SERVICE_NAME -f"
echo ""
echo -e "${YELLOW}Permission test (run as regular user — should fail):${NC}"
echo "  ls $INSTALL_DIR   ← expected: Permission denied"
