#!/bin/bash
# ============================================================
#  SOC Agent — macOS Installer (Protected Install)
#  Must be run as root:  sudo bash install_service_mac.sh <MANAGER_IP> <AGENT_NUM> <MACHINE_NAME>
#  Example:              sudo bash install_service_mac.sh 192.168.1.100 3 mac-lab-3
#
#  Installs to: /Library/SocAgent/  (root:wheel, chmod 700 — admin-only access)
#  Usage:
#    sudo bash install_service_mac.sh <MANAGER_IP> <AGENT_NUM> <MACHINE_NAME>
#    sudo bash install_service_mac.sh --uninstall
# ============================================================

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

PLIST_LABEL="com.soc.agent"
PLIST_PATH="/Library/LaunchDaemons/${PLIST_LABEL}.plist"
INSTALL_DIR="/Library/SocAgent"
REPO_URL="https://github.com/msuryawanshi05/soc-agent-deploy.git"

# ── Root check ────────────────────────────────────────────────────────────────
if [ "$(id -u)" != "0" ]; then
    echo -e "${RED}ERROR: Must run as root. Use: sudo bash $0 $*${NC}"
    exit 1
fi

# ── Uninstall ─────────────────────────────────────────────────────────────────
if [ "$1" = "--uninstall" ]; then
    echo -e "${YELLOW}[Uninstall] Removing SOC Agent LaunchDaemon...${NC}"
    launchctl unload "$PLIST_PATH" 2>/dev/null || true
    rm -f "$PLIST_PATH"
    # Strip permissions before removing
    chmod -R 755 "$INSTALL_DIR" 2>/dev/null || true
    rm -rf "$INSTALL_DIR"
    echo -e "${GREEN}✅ SOC Agent removed.${NC}"
    exit 0
fi

# ── Argument check ────────────────────────────────────────────────────────────
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
    echo "Usage: sudo bash $0 <MANAGER_IP> <AGENT_NUMBER> <MACHINE_NAME>"
    echo "       sudo bash $0 --uninstall"
    echo "Example: sudo bash $0 192.168.1.100 3 mac-lab-3"
    exit 1
fi

MANAGER_IP=$1
AGENT_NUM=$2
MACHINE_NAME=$3
AGENT_ID="agent-$(printf '%03d' $AGENT_NUM)"

echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${GREEN}  SOC Agent Installer (macOS — Protected)${NC}"
echo -e "${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${YELLOW}Manager IP :${NC} $MANAGER_IP"
echo -e "${YELLOW}Agent ID   :${NC} $AGENT_ID"
echo -e "${YELLOW}Hostname   :${NC} $MACHINE_NAME"
echo -e "${YELLOW}Install dir:${NC} $INSTALL_DIR"

# ── Step 1: Auto-detect Python ────────────────────────────────────────────────
echo -e "\n${GREEN}[1/7] Detecting Python...${NC}"
PYTHON=$(which python3 2>/dev/null || which python 2>/dev/null || true)
if [ -z "$PYTHON" ]; then
    echo -e "${RED}ERROR: Python 3 not found. Install via: brew install python3${NC}"
    exit 1
fi
echo -e "      Found: $PYTHON ($($PYTHON --version 2>&1))"

# ── Step 2: Check / install Git ──────────────────────────────────────────────
echo -e "${GREEN}[2/7] Checking Git...${NC}"
if ! command -v git &>/dev/null; then
    echo -e "      Git not found — installing Xcode command-line tools (includes git)..."
    xcode-select --install 2>/dev/null || true
    # Wait a moment and re-check
    sleep 5
    if ! command -v git &>/dev/null; then
        echo -e "${RED}ERROR: Git not found. Install from https://git-scm.com or via: brew install git${NC}"
        exit 1
    fi
fi
GIT=$(which git)
echo -e "      Git: $GIT"

# ── Step 3: Clone / update install directory ──────────────────────────────────
echo -e "${GREEN}[3/7] Setting up install directory ($INSTALL_DIR)...${NC}"
if [ -d "$INSTALL_DIR/.git" ]; then
    # Temporarily open permissions to allow git operations
    chmod -R 755 "$INSTALL_DIR"
    git -C "$INSTALL_DIR" fetch origin --quiet
    git -C "$INSTALL_DIR" reset --hard origin/main --quiet
    echo -e "      Repository updated."
else
    rm -rf "$INSTALL_DIR"
    git clone "$REPO_URL" "$INSTALL_DIR" --quiet
    echo -e "      Repository cloned."
fi

# ── Step 4: Write .env ───────────────────────────────────────────────────────
echo -e "${GREEN}[4/7] Writing .env configuration...${NC}"
cat > "$INSTALL_DIR/.env" << EOF
# Auto-generated by install_service_mac.sh for $MACHINE_NAME
MANAGER_HOST=$MANAGER_IP
MANAGER_PORT=9000
AGENT_ID=$AGENT_ID
AGENT_HOSTNAME=$MACHINE_NAME
AGENT_SEND_INTERVAL=1
MONITOR_BROWSER_HISTORY=true
MONITOR_ACTIVE_WINDOW=true
MONITOR_USB_DEVICES=true
MONITOR_SHELL_COMMANDS=true
MONITOR_PROCESSES=true
EOF
echo -e "      .env written."

# ── Step 5: Install pip deps + compile .py → .pyc ────────────────────────────
echo -e "${GREEN}[5/7] Installing dependencies and compiling to .pyc...${NC}"
$PYTHON -m pip install -r "$INSTALL_DIR/requirements.txt" --quiet
$PYTHON -m compileall "$INSTALL_DIR" -q
echo -e "      Dependencies installed and .pyc compiled."

# ── Step 6: Lock down permissions ─────────────────────────────────────────────
echo -e "${GREEN}[6/7] Applying access restrictions...${NC}"
chown -R root:wheel "$INSTALL_DIR"
chmod -R 700 "$INSTALL_DIR"
echo -e "      Owner: root:wheel | Permissions: 700 (admin-only access)"

# ── Step 7: Write and load LaunchDaemon ──────────────────────────────────────
echo -e "${GREEN}[7/7] Registering LaunchDaemon ($PLIST_LABEL)...${NC}"

launchctl unload "$PLIST_PATH" 2>/dev/null || true

AGENT_SCRIPT="$INSTALL_DIR/agent/agent.py"

cat > "$PLIST_PATH" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${PLIST_LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>${PYTHON}</string>
        <string>${AGENT_SCRIPT}</string>
    </array>

    <key>WorkingDirectory</key>
    <string>${INSTALL_DIR}</string>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <true/>

    <key>ThrottleInterval</key>
    <integer>10</integer>

    <key>StandardOutPath</key>
    <string>/var/log/soc-agent.log</string>

    <key>StandardErrorPath</key>
    <string>/var/log/soc-agent-error.log</string>
</dict>
</plist>
EOF

chown root:wheel "$PLIST_PATH"
chmod 644 "$PLIST_PATH"
launchctl load "$PLIST_PATH"
sleep 2

# ── Verify ────────────────────────────────────────────────────────────────────
echo -e "\n=== Verification ==="
RUNNING=$(launchctl list | grep "$PLIST_LABEL" || echo "")
if [ -n "$RUNNING" ]; then
    echo -e "${GREEN}✅ SOC Agent is RUNNING as LaunchDaemon.${NC}"
    echo "$RUNNING"
else
    echo -e "${YELLOW}⚠️  LaunchDaemon loaded — check logs if not visible yet:${NC}"
    echo "  sudo tail -f /var/log/soc-agent.log"
fi

echo ""
echo -e "${GREEN}✅ SOC Agent installed.${NC}"
echo -e "   Path     : $INSTALL_DIR (chmod 700 root:wheel)"
echo -e "   Daemon   : $PLIST_LABEL — auto-start + auto-restart"
echo -e "   Updates  : agent pulls from GitHub on every boot"
echo ""
echo -e "${YELLOW}Commands:${NC}"
echo "  sudo launchctl list | grep $PLIST_LABEL"
echo "  sudo launchctl unload $PLIST_PATH   ← stop (root only)"
echo "  sudo tail -f /var/log/soc-agent.log ← live logs"
echo "  sudo bash $0 --uninstall            ← remove completely"
